### ISSUE TITLE
Unable to select tokens within playground

### ISSUE THREAD

**Issue by dev3535** [reddec/trusted-cgi-ui#1]
https://github.com/reddec/trusted-cgi-ui/blob/32251c77ab4c14ab7e4ae6991a076b44c202f704/src/components/widgets/Playground.vue#L12

Since version 0.3.5 the tokens have been removed from the manifest and moved to the policies. So unable to run with authorization tokens. Als unable to override with manual headers, because the "authorization" header entry gets overridden by the `this.token` which cannot be selected.

So only way to use playground is without active policy.

**Comment by reddec** [comment]
Fixed in v0.3.6
Thanks for report!
